open_source_feed:
    resource: "@OpenSourceFeedBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
logout:
    path: /logout
