<?php

namespace OpenSource\FeedBundle\Entity;

/**
 * NewsLetterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsLetterRepository extends \Doctrine\ORM\EntityRepository
{
}
