<?php

namespace OpenSource\FeedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends EntityRepository
{
  public function findSubcategroyByCategory($category) {
    $qb = $this->_em->createQueryBuilder();
    $qb->select('s')
        ->from('Subcategory', 's')
        ->where('s.category.name = :category')
        ->setParameters(array(':category' => $category));

    return $qb->getQuery()->getArrayResult();
  }
}
