<?php

namespace OpenSource\FeedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoryRepository extends EntityRepository
{
}
